#!/usr/bin/env bash

set -euo pipefail

echo "==> Scanning directory $1 with ClamAV and maldet"

clamscan "$1"

echo "OK: ClamAV found no malware in $1"

maldet -a "$1"
ls -lah /usr/local/maldetect/logs/*

echo "OK: maldet found no malware in $1"
